### PR TITLE
Version sans prob

### PR DESCRIPTION
**Pull request by KBenMessaoud**

### CODE REVIEW

**Comment by MariemMARZOUGUI** [comment]
I have tried to repull but the second check has failed again I don't know why

**Comment by massimotisi** [comment]
Please start by removing all the "System.out" from the code of your team

**Comment by massimotisi** [comment]
Not accepting because the code does not pass the tests. The error is: `Exception in thread "main" java.lang.OutOfMemoryError: Java heap space`. This often means that there is an infinite loop.

You can read the error message by clicking on Details near to the failed check. Then click on Build with Ant to see the output of the test execution. You can run the same tests on your Eclipse, they are test/abstraction/FiliereParDefaultTest.java and test/presentation/FenetrePrincipaleTest.java. To run them: right-click on build.xml -> Run As -> Ant Build. You will see the error message in the console. Fix the error, then commit and push.

**Comment by MariemMARZOUGUI** [comment]
Is it possible that in this case the error is not from our file? because i don't seem to see an infinite loop in our file

**Comment by massimotisi** [comment]
I looked into your code. It's not an infinite loop but your code consumes all the resources allocated to us by github. Try to optimize it. As an indicator, in your Eclipse you will find a file tempsEquipes.json that shows how much time each team uses. You will see that your team uses much more than the others.

**Pull request merged**
