### PR TITLE
seance 12/04

### PR DESCRIPTION
**Pull request by elouanzer**

### CODE REVIEW

**Review by massimotisi — CHANGES_REQUESTED** [review]
You are changing files outside of your java package. You can see the files that you are changing in the "Files changed" tab of your pull request on the github website. This list must contain only files in your package.

You can replace these files with the version from the main repository. To do that, right click on these files or folders -> Replace with -> Branch, Tag or Reference -> Remote tracking -> select the main repository (not your team repository) -> Replace. Then commit and push to your repository. Don't close the pull request, it will be automatically updated.

Note that if the files you changed are not Java files, they will be hidden in the Java perspective of Eclipse. To see and edit them, switch to the Resource perspective of Eclipse.

**Comment by elouanzer** [comment]
> 



> You are changing files outside of your java package. You can see the files that you are changing in the "Files changed" tab of your pull request on the github website. This list must contain only files in your package.
> 
> You can replace these files with the version from the main repository. To do that, right click on these files or folders -> Replace with -> Branch, Tag or Reference -> Remote tracking -> select the main repository (not your team repository) -> Replace. Then commit and push to your repository. Don't close the pull request, it will be automatically updated.
> 
> Note that if the files you changed are not Java files, they will be hidden in the Java perspective of Eclipse. To see and edit them, switch to the Resource perspective of Eclipse.

It should be good  now

**Comment by massimotisi** [comment]
it's not good yet, please look in the "Files changed" tab of your pull request on the github website. This list must contain only files in your package.

**Comment by elouanzer** [comment]
> it's not good yet, please look in the "Files changed" tab of your pull request on the github website. This list must contain only files in your package.

ok sorry, what about now ? the file disappeared of the list

**Review by massimotisi — APPROVED** [review]

**Comment by massimotisi** [comment]
> > it's not good yet, please look in the "Files changed" tab of your pull request on the github website. This list must contain only files in your package.
> 
> ok sorry, what about now ? the file disappeared of the list

Now that's ok. 

There is still an error ""This branch is out-of-date with the base branch"". Your team repository is not up-to-date with the changes that happened on the main repository. Please pull from the main repository and then push to the team repository.

**Comment by elouanzer** [comment]
> > > it's not good yet, please look in the "Files changed" tab of your pull request on the github website. This list must contain only files in your package.
> > 
> > 
> > ok sorry, what about now ? the file disappeared of the list
> 
> Now that's ok.
> 
> There is still an error ""This branch is out-of-date with the base branch"". Your team repository is not up-to-date with the changes that happened on the main repository. Please pull from the main repository and then push to the team repository.

ok this is done. Tell me when i can close the pull request

**Comment by massimotisi** [comment]
You never need to close the pull request. If it's accepted, it is closed automatically.

**Pull request merged**
